import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

import Sprint1 from '../components/Sprint1'

export default function Home() {
  const [sprintSelected, setSprintSelected]=useState(null)

  function selectSprint(sprintNum){
    setSprintSelected(sprintNum);
  }
  let containerContent;
  if(sprintSelected == null){
    containerContent = <div className="message"><span className="please">Please select a sprint to start</span><img className="arrow" width="300px" src="https://visualpharm.com/assets/112/Up-595b40b85ba036ed117db6cd.svg"/></div>
  } if(sprintSelected == 1){
    containerContent = <Sprint1/>
      
  }
  return (
    <div>
      <Head>
        <title>Christian Chitanu - PetClinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;1,400&family=Quicksand:wght@300&display=swap" rel="stylesheet"/>
      </Head>
    
      <div id="wrapper">
      <nav id="navbar"><span className="navItem logo">Christian Chitanu&apos;s<br/>PetClinic E-Portfolio</span> <span className="navItem link"><a onClick={()=>selectSprint(1)}>Sprint 1</a></span></nav>
        <div className="container">
          {containerContent}
        </div>
      </div>
    </div>
  )
}
