import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import styles from '../styles/Home.module.css'

import Sprint1 from '../components/Sprint1'
import Sprint2 from '../components/Sprint2'
import Sprint3 from '../components/Sprint3'

export default function Home() {
  const [sprintSelected, setSprintSelected]=useState(null)

  function sprintHoverSelect(sprintNum){
    if(sprintSelected == null){
      if(sprintNum == 1){
        document.querySelector(".arrow").style.left = "-115px";
      }
      if(sprintNum == 2){
        document.querySelector(".arrow").style.left = "0px";
      }
      if(sprintNum == 3){
        document.querySelector(".arrow").style.left = "115px";
      }
    }
  }
  function sprintHoverLeave(){
    if(sprintSelected == null){
      document.querySelector(".arrow").style.left = "0px";
    }
  }
  function selectSprint(sprintNum){
    setSprintSelected(sprintNum);
  }
  let containerContent;
  if(sprintSelected == null){
    containerContent = <div className="message"><span className="please">Please select a sprint to start</span><img className="arrow" width="100px" src="https://visualpharm.com/assets/112/Up-595b40b85ba036ed117db6cd.svg"/></div>
  } if(sprintSelected == 1){
    containerContent = <Sprint1/>
      
  } if(sprintSelected == 2){
    containerContent = <Sprint2/>
  }
  if(sprintSelected == 3){
    containerContent = <Sprint3/>
  }
  return (
    <div>
      <Head>
        <title>Christian Chitanu - PetClinic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={true}/>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,300;1,400&family=Quicksand:wght@300&display=swap" rel="stylesheet"/>
      </Head>
    
      <div id="wrapper">
      <nav id="navbar"><span className="navItem logo">Christian Chitanu&apos;s<br/>PetClinic E-Portfolio</span> 
      <div className="navItemContainer">
      <span className="navItem link"><a onMouseLeave={()=>sprintHoverLeave()} onMouseEnter={()=>sprintHoverSelect(1)} onClick={()=>selectSprint(1)}>Sprint 1</a></span>
      <span className="navItem link"><a onMouseLeave={()=>sprintHoverLeave()} onMouseEnter={()=>sprintHoverSelect(2)} onClick={()=>selectSprint(2)}>Sprint 2</a></span>
      <span className="navItem link"><a onMouseLeave={()=>sprintHoverLeave()} onMouseEnter={()=>sprintHoverSelect(3)} onClick={()=>selectSprint(3)}>Sprint 3</a></span>
      </div>
      </nav>
        <div className="container">
          {containerContent}
        </div>
      </div>
    </div>
  )
}
